#更新状態
!system 2000  ------------------------
!system 2001  ADS 1103 Gateball Client
!system 2002  ------------------------
!system 2003  @YGOPro1103
!system 2004  Last update : 2024-01-14

#仮実装のカテゴリやカウンター

#カテゴリ(仮)

#カテゴリ(正規予定)

#カウンター

#特殊勝利